[package]
name = "greetings_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

greetings = { path = "../greetings" }
greetings_derive = { path = "../greetings/greetings_derive" }
